[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
temp_project = "APP6a8Kk5cwhTY3XYKhVDBHZA86XWBhe4L7NthXiH5QY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
